### ISSUE TITLE
Add Docker pull command: `docker-update` 

### ISSUE THREAD

**Issue by evansd** [opensafely-core/opensafely-cli#10]
Better name tbd.

At present the `run` command automatically runs `docker pull` when you're about to run an action requiring a docker image which you don't have locally. But by design it doesn't automatically check for updates as:
 * it's slow;
 * it won't work offline;
 * it's not ideal to have docker images change out from under you suddenly;
 * it's hard to provide a nice UI for as it's hard to determine beforehand whether docker will need to pull anything and if you don't hide it's output you get useless noise in the console and if you _do_ hide its output then it just appears to be hanging when pulling large images.

Obviously we can just get users to run `docker pull` themselves but it would be nice to abstract this for them and nice to keep ghcr.io as an implementation detail.

So we should provide a command which goes through all available OpenSAFELY images, checks which ones you have pulled locally and updates each of those. Ones which you haven't yet installed will automatically pull in the latest version the first time you need them so we don't need to worry about those.

**Comment by evansd** [comment]
Just thinking about it `opensafely pull` might be the best option. It makes sense to use the docker terminology rather than `update` (and we also have updating a project repo to the latest format, and updating opensfely-cli itself as commands we may need to support).

**Comment by bloodearnest** [comment]
It should probably also be able to do some clean up and pruning of our images locally, to help the user reduce space usage.
e.g. it could remove old docker.opensafely.org or ghcr.io/opensafely/ tags in the first instance.

**Comment by bloodearnest** [comment]
Closed in #31
