### ISSUE TITLE
Add with_gp_consultations to restricted dataset

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/opensafely-cli#120]
requested by @brianmackenna

**Comment by sebbacon** [comment]
Can we add some text to [the docs](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.with_gp_consultations) to avoid people being surprised? @brianmackenna may have views on the appropriate wording

**Comment by Jongmassey** [comment]
After discussion with data team colleagues, it seems like making this a **restricted** function is not the right approach - it is likely to cause lots of extra work for those receiving the restricted dataset usage notifications (mainly me) and much user consternation given the wide usage of this function.

**Comment by Jongmassey** [comment]
After discussion with data team colleagues, it seems like making this a **restricted** function is not the right approach - it is likely to cause lots of extra work for those receiving the restricted dataset usage notifications (mainly me) and much user consternation given the wide usage of this function.

**Comment by Jongmassey** [comment]
After discussion with data team colleagues, it seems like making this a **restricted** function is not the right approach - it is likely to cause lots of extra work for those receiving the restricted dataset usage notifications (mainly me) and much user consternation given the wide usage of this function.

**Comment by HelenCEBM** [comment]
Can do but I'm not sure any of us know much about it. Who's got the best understanding of the issues? @alexwalkerepi ?

**Comment by alexwalkerepi** [comment]
I agree that making it a restricted dataset is not the right approach.

There's a health warning in the docs already that I could slightly add detail to and better express the uncertainty around it. There are ongoing conversations about "better" measures of consultation volume, that are on my list to nudge along. This, combined with some work looking at the actual data to better characterise it is probably the ultimate aim.

Until then the best we can to is "we know it probably has a few issues but it's all a bit unknown :shrug:"

**Comment by Jongmassey** [comment]
There are [62 usages](https://github.com/search?l=Python&q=org%3Aopensafely+with_gp_consultations&type=Code) of this function in study definitions in the OpenSAFELY github org. 

What I have in mind is some sort of reusable function to ascertain usages of particular functions/patterns, the repositories in which they exist, and the users associated with them so that an email (or similar) notification may be sent when necessary. For example, the erroneous IMD rounding pattern might also make use of such a function.

From some quick prototyping with the GitHub API it seems like this is pretty possible (albeit with our researcher lookup sheet containing usernames), but am aware others might have already written similar things

**Comment by sebbacon** [comment]
It sounds like you've missed the existence of the tool @inglesp made to do exactly this filesystem-based version, @iaindillingham? (I can't find a link to it now but Peter can probably help)

**Comment by inglesp** [comment]
Here it is in its latest incarnation: https://github.com/opensafely-core/sysadmin/blob/main/repoupdater.py

**Comment by Jongmassey** [comment]
- [ ] Strengthen wording in the docs
- [ ] Identify users and emails
- [ ] Notify above with updated wording

**Comment by Jongmassey** [comment]
@sebbacon @brianmackenna @HelenCEBM https://github.com/opensafely/documentation/pull/820 is this adequately strongly worded in your esteemed opinions?

**Comment by sebbacon** [comment]
I feel it could be even stronger and succinct. How about:

>A "consultation" as returned by this function may not actually be a consultation between a health care professional and patient.
>
>For example, simple administrative tasks such as updating a patient's details may also cause creation of a "consultation" record.
>
> It is, therefore, extremely unlikely you can use this field to infer anything about real clinician-patient interactions, and it is even more difficult to compare activity between practices as recording behaviour can vary. Some EHRs even delete consultation data for a patient when they switch practice.

**Comment by Jongmassey** [comment]
@brianmackenna   @sebbacon  what are your thoughts on emailing the above list notifying them that we have updated the documentation with a gentle reminder of the limitations of what constitutes a "consultation"

**Comment by sebbacon** [comment]
I think it's a good idea

**Comment by Jongmassey** [comment]
https://gist.github.com/Jongmassey/dbf708b1eafe885191bc2bbe75d58112

**Comment by iaindillingham** [comment]
Alas, I don't think so: at least not without changing how the docs are built.

**Comment by inglesp** [comment]
I've move the warning to the top of the docs.  (See PRs linked above.)

Have also drafted an email in [this doc](https://docs.google.com/document/d/1Qbkv2nDGdyJJ1E5_8OyeRIuv5zmARABBxEaNOHAzf-A/edit).

@brianmackenna please could you take a look?

**Comment by brianmackenna** [comment]
Warning
Should the text be in the warning box similar to one above in this screenshot
![image](https://user-images.githubusercontent.com/40460354/179960824-532e4be4-737f-44bf-93e5-8fc6346c4c53.png)

email
Looks great  - I have made some slight tweaks. I think we always knew this so it isn't new information to us.

**Comment by inglesp** [comment]
> Should the text be in the warning box similar to one above in this screenshot

That's going to be a bit too hard, sorry.

> email... Looks great - I have made some slight tweaks

These look good, thanks.

**Comment by inglesp** [comment]
Have emailed all users identified by Jon.  See here https://groups.google.com/u/1/a/opensafely.org/g/team/c/_qOZvX4Zqck.
