### ISSUE TITLE
Finish `opensafely exec` implementation

### ISSUE THREAD

**Issue by evansd** [opensafely-core/opensafely-cli#149]
The [long-discussed](https://github.com/opensafely-core/opensafely-cli/issues/18) `opensafely exec` command was finally implemented in:
 * #146

But there are further tasks before this is ready for general consumption:
 * Undo the quick fix and implement the proper solution for the "TTY problem" #148
 * Document the `exec` command
 * Rebuild all Docker images from the latest base-docker so they include [this fix](https://github.com/opensafely-core/base-docker/pull/17) which allows them to run as non-root.
 * Check that all images _can_ be run as non-root — they should be able to but there might be some unpleasant surprises that need fixing.
 * Consider the extra features mentioned in the original PR (though we may not want to do any right now):
   - Adding an `--entrypoint` argument to allow customising the image entrypoint for debugging purposes.
   - Passing the appropriate product key for the `stata-mp` image.
   - Setting the `OPENSAFELY_BACKEND` environment variable to `expectations` as the local job-runner does.

**Comment by StevenMaude** [comment]
## Failed to write output

I tested this out. It looks useful but there's one quirk for me at the moment.

When I tried it as is, with the current `opensafely` (v1.32.1) and Data Builder (v0.57.0), it worked without the `--output` option, but not with.

When I try to write a CSV with the `--output` option, with the latest Data Builder image (v0.57.0), I get a permissions issue:

```sh
$ opensafely exec databuilder:v0.57.0 generate-dataset "./1a_minimal_dataset_definition.py" --dummy-tables "example-data/minimal" --output "outputs/1a_minimal_dataset_definition.csv"
```
```python
…
  File "/app/databuilder/file_formats/csv.py", line 16, in write_dataset_csv
    context = filename.open(mode="w", newline="")
  File "/usr/lib/python3.9/pathlib.py", line 1242, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1110, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'outputs/1a_minimal_dataset_definition.csv'
```

The same command with `opensafely run` *does* work:

```
databuilder:v0.57.0 generate-dataset "./1a_minimal_dataset_definition.py" --dummy-tables "example-data/minimal" --output "outputs/1a_minimal_dataset_definition.csv"
```

I believe this is a quirk of me running *rootless* Docker. I think [this very long and ancient open Moby issue partly discusses it](https://github.com/moby/moby/issues/2259). I suspect it's something like: the bind mount has the same uid and gid as the host, but the user in the container is mapped to a different id.

## Workaround

If I modify the `exec.py` to [just remove the `user_args`](https://github.com/opensafely-core/opensafely-cli/blob/da82af0af919344ae80e0533fd6266b52ddcafa1/opensafely/execute.py#L42) that specify `uid` and `gid`, then that does run the command and I can access the output CSV. :heavy_check_mark:

So the quick fix workaround here would be some way of disabling the `--user` part of the command, maybe by an environment variable or command line option.

**Comment by bloodearnest** [comment]
Fixed in #171 171

**Comment by bloodearnest** [comment]
Bah, I forgot about OPENSAFELY_BACKEND

**Comment by bloodearnest** [comment]
https://github.com/opensafely-core/opensafely-cli/pull/172
