### ISSUE TITLE
Put project root directory on `PYTHONPATH` when running `opensafely jupyter`

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/opensafely-cli#160]
It would be useful to put the project root directory (the value of `--directory`) on the `PYTHONPATH` when running `opensafely jupyter`, so that scripts can be imported as modules.

Why? [opensafely/appointments-short-data-report](https://github.com/opensafely/appointments-short-data-report) defines `OUTPUT_DIR` in _analysis/\_\_init\_\_.py_. If a script is invoked as a module (`python -m a_script`), then `OUTPUT_DIR` can be accessed with a relative import (e.g. `from .. import OUTPUT_DIR`). However, the same isn't true when running `opensafely jupyter`, because it's not possible to put the project root directory on the `PYTHONPATH`.

**Comment by lucyb** [comment]
@bloodearnest to dig into this a bit more and come up with suggestions for possible solutions.

**Comment by bloodearnest** [comment]
So, I'm looking at adding this, as I think it's probably a useful thing in general.

However, I'm very suspect of using the import mechanism to have global study variables.  Importing modules as config is full of horrible corner cases and gotchas, exactly like this issue.

But fixing that is another issue: https://github.com/opensafely-core/job-runner/issues/545

**Comment by bloodearnest** [comment]
The attached PR adds /workspace to the PYTHONPATH

However, this doesn't allow the relative `from .. import OUTPUT_DIR` to work in the example. Relative imports require a proper package structure to work, and are full of gotchas.

But it does allow `from analysis import OUTPUT_DIR` to work, which achieves the same goal, and is IMO more readablity.

I'd actually suggest not using the magic __init__, but instead adding `analysis/config.py`, and then use the `from analysis import config` and `config.OUTPUT_DIR` pattern when you needed it. I think that is much clearer about what file has the config in it, and is clear in use that this is a global config variable.

**Comment by bloodearnest** [comment]
Fixed in #173
