### ISSUE TITLE
Since version 1.32.4 the check for opensafely CLI being run in a Git repo is too strict / not necessary for some subcommands

### ISSUE THREAD

**Issue by remlapmot** [opensafely-core/opensafely-cli#176]
Since version 1.32.4 there seems to be new a check for being in a Git repo. E.g. under version 1.32.5, run in a directory which is not Git initialised
```
pip install opensafely==1.32.5
opensafely --version
```
produces
```
opensafely --version
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
opensafely v1.32.5
```

Whereas under version 1.32.3 the following run in a directory which is not Git initialised 
```
pip install opensafely==1.32.3
opensafely --version
```
just gave
```
opensafely v1.32.3
```

I would say that a subset of commands do not require being run in a Git repo. I would say those are at least
* `opensafely upgrade`
* `opensafely -h`
* `opensafely --help`
* `opensafely help`
* `opensafely --version`
* `opensafely pull`
* `opensafely info`

So I would suggest removing the check for being in a Git repo for those commands.

Additionally the `fatal: ...` warning message is not correct because the command does not exit with an error which the `fatal: ...` wording suggests.

**Comment by bloodearnest** [comment]
This is an issue with job-runner, and was fixed here: https://github.com/opensafely-core/job-runner/pull/547
