### ISSUE TITLE
`ipython` run by `opensafely exec` doesn't have tab-completion

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/opensafely-cli#184]
I'm unsure whether this is an issue with the OS Python Docker image, or with the OS CLI. Nevertheless, if I run...

```sh
opensafely exec python:latest ipython
```

...then I find myself in an IPython shell. However, this shell doesn't have tab-completion, which is unhelpful. I've drifted back to running...

```sh
docker run --rm --interactive --tty --entrypoint ipython --volume $(pwd):/workspace ghcr.io/opensafely-core/python
```

...which does have tab-completion.

I've run `opensafely upgrade` and `opensafely pull`, so am confident that I have the latest versions of the Python Docker image and the CLI. I'm not sure how tab-completion works; could it be related to filesystem permissions?

**Comment by bloodearnest** [comment]
Quick note: `opensafely exec python ipython` does have tab completion for me on Ubuntu

**Comment by iaindillingham** [comment]
Not for me on macOS 🙁

**Comment by lucyb** [comment]
Note: this is currently blocking Iain from writing a blog post about using exec in iPython (not suggesting we change the priority right now, just for information)

**Comment by iaindillingham** [comment]
It's a soft block - if it works for people who aren't using macOS, then I'm happy to call Docker directly, rather than going via `opensafely exec`. My hunch, though, is that we have several users who would be interested in using `opensafely exec` who also use macOS (Louis, Milan, and Lisa come to mind).

**Comment by remlapmot** [comment]
Hi Iain

Would you be on an Apple Silicon Mac?

On my M1 Mac I find that if I enable the new Rosetta for Linux beta feature in Docker settings that the tab completion seems to work for me whereas it does not work under the standard emulation (this beta feature is disabled by default).

Go to Docker Dashboard, then settings cog, then Features in Development, then Beta features and click check box and Apply & restart.

<img width="1225" alt="dd-screenshot" src="https://user-images.githubusercontent.com/3777473/214650632-7a4526f2-ffab-4dfe-ad4c-48df0a2c1a15.png">

**Comment by iaindillingham** [comment]
> Would you be on an Apple Silicon Mac?

Hello @remlapmot 👋🏻 I'm afraid not. I'm on an Intel 🦕

**Comment by remlapmot** [comment]
Interesting, that has me stumped.

Additionally, I find that the tab completion works on Windows (11) and within Windows Subsystem for Linux (running Ubuntu 20.04).

**Comment by bloodearnest** [comment]
It works on windows for me too, from CMD, git-bash and powershell terminals.

On all systems I tested, I did have to press tab a few times for the completions to show up, and then they show up a few times.

It's possible it's slow building a cache of potential completions on first invocation? If so, that might be something we can prebake into the python image, if that's useful.

**Comment by remlapmot** [comment]
Simon is right - sorry I was impatient on my M1 Mac. Disabling Rosetta for Linux - it does in fact work - there's just a much longer pause than when Rosetta for Linux is enabled - I should have waited a bit longer.

**Comment by remlapmot** [comment]
Related to the OpenSAFELY blog - I was wondering does it have an RSS/XML/Atom feed? I couldn't find one, e.g. there's no https://www.opensafely.org/blog/index.xml

The Bennett site has an *index.xml* at its top level
https://www.bennett.ox.ac.uk/blog/
https://www.bennett.ox.ac.uk/index.xml

I guess most visitors don't use feed readers anymore so it's not really important.

**Comment by iaindillingham** [comment]
Just to check (I should have been clearer, earlier) the standard library completes; but not, say, Pandas.

```python
import pandas
pandas.  # tab
```

Above, tabbing during `import` and `pandas` will complete; but tabbing after the dot won't. From your comments, I think that isn't the case on other platforms.

**Comment by bloodearnest** [comment]
> Related to the OpenSAFELY blog - I was wondering does it have an RSS/XML/Atom feed? I couldn't find one, e.g. there's no https://www.opensafely.org/blog/index.xml
> 
> The Bennett site has an _index.xml_ at its top level https://www.bennett.ox.ac.uk/blog/ https://www.bennett.ox.ac.uk/index.xml
> 
> I guess most visitors don't use feed readers anymore so it's not really important.

https://www.opensafely.org/changelog/index.xml

**Comment by bloodearnest** [comment]
> Just to check (I should have been clearer, earlier) the standard library completes; but not, say, Pandas.
> 
> ```python
> import pandas
> pandas.  # tab
> ```
> 
> Above, tabbing during `import` and `pandas` will complete; but tabbing after the dot won't. From your comments, I think that isn't the case on other platforms.

I occurred to me last night that it might be specific things that don't complete.

This fails to suggest completions for me on linux too.

If I do `opensafely exec -u 0 python ipython`, it does work, so it is definitely todo with file permissions when not running as root. Progress!

**Comment by bloodearnest** [comment]
Found the issue - when running as non-root user, you don't have a valid HOME dir, which ipython relies on to write stuff.

Completion work for me with this: `opensafely exec -e HOME=/tmp python ipython`

We can add a default HOME=/tmp to the image, easy fix

**Comment by iaindillingham** [comment]
Brilliant! Thank you 🙂
