### ISSUE TITLE
opensafely pull failing on recent docker

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/opensafely-cli#219]
Users reporting `opensafely pull` failing on recent docker.

The command `docker images "ghcr.io/opensafely-core/*"` didn't work for Milan on recent Docker for Mac. But it did work for Tom W on mac

Might just be oddness on Milan's machine

Slack discussion: https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1692883767199129

**Comment by madwort** [comment]
nb. TomW is on x86 macos & Milan is on arm macos.
