### ISSUE TITLE
Make a self-contained executable so users don't have to install Python

### ISSUE THREAD

**Issue by evansd** [opensafely-core/opensafely-cli#22]
(Though we should continue to support pip installation as for users who _do_ already have Python that's even easier.)

Options include [PyOxidizer](https://pyoxidizer.readthedocs.io/en/stable/) (new hotness) and [PyInstaller](https://github.com/pyinstaller/pyinstaller) (which we've used successfully in the past).

Possibly useful links for PyInstaller:
 * https://github.com/ebmdatalab/datalab-notebook-template
 * https://simonwillison.net/2021/Jan/10/weeknotes/

One thing we need to consider is how users update their version of `opensafely` once they've installed it. Ideally this would be done via on `opensafely update` command or equivalent. [PyUpdater](https://www.pyupdater.org/) might help with this.

**Comment by sebbacon** [comment]
In case it's useful, [here's a GHA workflow from when we last used it](https://github.com/opensafely/cohort-extractor/blob/2a3606474b7739b70608c194c1251e4b409b05af/.github/workflows/windows_build_and_release.yaml)

Note using GH releases to push build outputs.

**Comment by evansd** [comment]
In order to make binaries runnable on macOS it looks like they need to be [signed and notarised](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution). This will require an Apple Developer account and some CI faff. There are some useful notes and examples here:
https://github.com/simonw/datasette/issues/1171#issuecomment-754911290

I suggest that for now we ignore macOS (and continue to recommend `pip install`) and just concentrate on Windows.

**Comment by evansd** [comment]
Other notes:

PyInstaller's single-file executable mode, while convenient, apparently adds a noticeable start-up overhead each time the command is run, which may not be great for our purposes.

[cx_freeze](https://github.com/marcelotduarte/cx_Freeze) is another option worth looking it. It can create simple installers directly with its `build_msi` command which avoids needing a separate tool for this. However, given that we'll probably want to customise the installer to a greater degree than cx_freeze allows, this is maybe not that helpful.

[Inno Setup](https://jrsoftware.org/isinfo.php) is probably the thing we want to use for creating an installer.

**Comment by sebbacon** [comment]
> PyInstaller's single-file executable mode, while convenient, apparently adds a noticeable start-up overhead each time the command is run, which may not be great for our purposes.

Can confirm, at least a second each time IIRC, but perhaps people will put up with this!

**Comment by evansd** [comment]
> One thing we need to consider is how users update their version of opensafely once they've installed it. Ideally this would be done via on opensafely update command or equivalent. PyUpdater might help with this.

We now have an `opensafely upgrade` command, plus an automated check for new versions. However, this assumes that it's been installed via pip and invokes pip for the upgrade so we'll need to think through how this will work.

**Comment by StevenMaude** [comment]
> However, this assumes that it's been installed via pip and invokes pip for the upgrade so we'll need to think through how this will work.

Especially as some, maybe developers, might have both versions installed.

Is there a reliable way to distinguish a command run with one of the executable packagers, versus installed Python?

A simple approach could be checking the filename via `sys.executable` but that won't work if the file is renamed. Or maybe size of the executable, although may not be reliable?

Otherwise maybe a Boolean could be overridden — `PIP_INSTALLED=True` — or similar. In Go, this can be [done at build](https://stackoverflow.com/a/28460195)); less sure how you'd do the same in Python without just using `sed` or similar to edit the variable and then build an executable. That could be at build time, or something set post-`pip install` somehow?

---

I'd add that though the macOS signing process is tedious, signing Windows executables on Linux is not that bad. I tried [osslsigncode](https://github.com/mtrojnar/osslsigncode) fairly recently and it worked. However, I'm not sure what the barriers for potential users to jump through and whether "you should only run signed .exes" is a hurdle that people have in their organisations

There's also this type of security [fun and games](https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg) with potential antivirus false positives too.

**Comment by evansd** [comment]
Ah, it sounds like you've had some recent experience with this which is good!

I think Windows is definitely the platform to focus on for now, and I'm picturing all sorts of fun and games relating to organisation policies/firewalls/antivirus in our future.

I think the macOS installation story is a bit more straightforward and that's also a smaller proportion of our users so less urgent. (Though it would be nice to make `brew install opensafely` a thing at some point.)

I think having an explicit flag to indicate installation method is, as you suggest, a better approach than trying to infer it. The exact mechanics of that will no doubt depend on the packaging method we use, but it will certainly be do able one way or the other.

**Comment by StevenMaude** [comment]
I had a quick look at the PyOxidizer documentation:

> The default Python distributions have been upgraded to CPython 3.8.6 (from 3.7.7) and support for Python 3.7 has been removed.
https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_history.html#version-0-8-0

If we wanted to use PyOxidizer, we probably should ensure that the tests pass in later Python versions (which they probably do); we only test on 3.7 currently.

**Comment by evansd** [comment]
Good point, done here: https://github.com/opensafely-core/opensafely-cli/pull/47

**Comment by iaindillingham** [comment]
Dumping this here, after a discussion about creating a self-contained executable for MG.

---

Candidate/rejected libraries are recommended by the Python Packaging User Guide:
<https://packaging.python.org/overview/#bringing-your-own-python-executable>

Suggestions:

* Check the version of macOS; v11 (Big Sur) or v10 (from Cheetah to Catalina)?
  We can only really support v11.
* Check the chip; Intel or M1?
  We can only really support Intel.
* Use pyinstaller (see below)
* Budget for a week FT for MVP
* Think about project next-steps e.g. Who maintains and how? What about Windows and Linux?

## Candidate libraries

* Name: pyinstaller
  Website: <http://www.pyinstaller.org/>
  Last released: April 17, 2021
  Notes:

  * Cross-platform
  * 3.5-3.9
  * "no user intervention required"; for most use cases?
  * code-signing
  * Single directory or single file
  * The install is specific to the OS pyinstaller was run from; how specific?
  * Does not bundle OS-specific external binaries (e.g. `git`)
  * The bootloader creates a console; would we interact with `opensafely run ...` here?
  * Icons!
  * Extensive documentation
  * 353 contributors

* cx_Freeze
  <https://marcelotduarte.github.io/cx_Freeze/>
  April 14, 2021

  * Cross-platform
  * 3.6-3.9
  * Single directory
  * The install is specific to the OS pyinstaller was run from; how specific?
  * Icons!
  * Concise documentation
  * 74 contributors

## Rejected libraries

* constructor
  <https://github.com/conda/constructor>
  May 24, 2021
  Command-line installer; Conda-specific

* py2exe
  <http://www.py2exe.org/>
  April 24, 2021
  Only builds Windows applications; must be run from Windows?

* py2app
  <https://py2app.readthedocs.io/en/latest/>
  April 6, 2021
  Only builds macOS applications; must be run from macOS

* bbfreeze
  <https://pypi.org/project/bbfreeze/>
  January 20, 2014
  No maintainer

* osnap
  <https://github.com/jamesabel/osnap>
  June 15, 2019
  Superceeded by pyship

* pyship
  <https://github.com/jamesabel/pyship>
  December 7, 2020
  Cross-platform; configuration in *pyproject.toml*; pushes artefacts to S3; concise documentation; one contributor

* pynsist
  <https://pypi.org/project/pynsist/>
  March 28, 2021
  Only builds Windows applications; 3.6-3.9

**Comment by iaindillingham** [comment]
Given that the amount of time it would take to create and maintain a self-contained Python executable is uncertain; that we haven't -- so far -- identified any major pitfalls with Gitpod; and that we're undertaking a week-long [tidy up project](https://github.com/orgs/opensafely-core/projects/5), I'm going to close this issue.

**Comment by evansd** [comment]
Are we closing this because we've officially decided we're not going to do it, or just because open issues are considered untidy?

**Comment by iaindillingham** [comment]
That's an excellent question. Perhaps @sebbacon or @benbc could comment?

**Comment by evansd** [comment]
I agree that the existence of gitpod makes this lower priority but, on the sort of "onion" model of making each layer of OpenSAFELY nice to use on it's own without having to buy into the whole shebang, I still think there's value in making the command easy to install locally.

**Comment by sebbacon** [comment]
Me, I'm quite a fan of closing things that aren't likely to get done in the next 12 months and I reckon this is one of them. It already existed in some other form about a year ago I think, and then resurfaced, so I'm sure it will again.

On the other hand, happy to keep it open too if you'd find it useful, OP!
