### ISSUE TITLE
Repeated requests to update codelists

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/opensafely-cli#228]
@kevwing reports[^1] repeated requests to update codelists. However, running `opensafely codelists update` doesn't update the codelists.

[^1]: https://bennettoxford.slack.com/archives/C010SJ89SA3/p1699358193496199?thread_ts=1699357017.320919&cid=C010SJ89SA3

**Comment by rebkwok** [comment]
Closing as it looks like this was related to the more-or-less concurrrent update of dm+d, and the codelists are now being reported as up to date

**Comment by iaindillingham** [comment]
Thanks, @rebkwok.
