### ISSUE TITLE
`run` fails  on windows with a cohort-joiner:v0.0.56 action

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/opensafely-cli#235]
Problem reported by Vicki Palin at Manchester who is using opensafely v1.41.0 

`[WinError 2] The system cannot find the file specified`

`cohortextractor` and `r` actions work fine, fails with above error when running an action that uses the cohort joiner image

[this](https://github.com/opensafely/uom_pregnancy_tx_pathways/blob/main/project.yaml) is the project yaml in question. `opensafely pull` doesn't pull in the cohort joiner image

Works fine on my machine (ubuntu 22.04.on WSL) and reportedly works fine for @alschaffer  as well.

**Comment by Jongmassey** [comment]
This behaviour is observed both in an out of an anaconda environment

**Comment by Jongmassey** [comment]
Also tested on my machine using windows 10 both in an out of an anaconda prompt and works fine for me.

UoM had a big data breach earlier in the year and rolled out a bunch of extremely restrictive group policies, some of which have now been rolled back but there may be some residual weirdness

**Comment by bloodearnest** [comment]
Hmm, there is no "cohort-joiner" image. It uses the python image.

Do they have the python image downloaded? `opensafely pull python`

Entirely possible our automatic-pull-image in local run is broken for actions, will investigate.

**Comment by Jongmassey** [comment]
`opensafely pull` only pulled the cohortextractor and R images, there's no python actions in their project.yaml

**Comment by Jongmassey** [comment]
I'll ask her to run `opensafely pull python` and see if that fixes it

**Comment by bloodearnest** [comment]
I just tested it, it works for me on linux. When I remove the python image, running the cohort-joiner actions does automatically re-download the python image.

**Comment by Jongmassey** [comment]
Vicki just messaged me to say that she gets the same error after pulling the python image

**Comment by evansd** [comment]
I don't think it's anything to do with the Python image. The `cohort-joiner` action needs to be checked out from git and I think we've had weird problems with that on Windows before.

This configures where the repo gets created:
https://github.com/opensafely-core/job-runner/blob/c44f6f8a5aeb2249f8c595dc6b20e6032326d34a/jobrunner/cli/local_run.py#L268-L276

It's possible that locating that directory and deleting it will fix the issue.

It would be useful to get more of a stack trace that just the `WinError`. Maybe a screenshot or something?

**Comment by bloodearnest** [comment]
Given there's a workaround in place for the user, going to close this, as there nothing we can work on without more info
