### ISSUE TITLE
Create a `python-jupyter` subcommand

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/opensafely-cli#29]
Many users will want to develop a jupyter notebook interactively against dummy (or self-supplied) data.

This should be done using the jupyter + python environment supplied in the relevant docker image runtime.

This requires an `opensafely-cli` subcommand for starting a jupyter notebook server. Ideally it would be possible to run this command several times in different consoles, for working on more than one project at once.

Therefore, the script needs to:

* Mount the current directory at `/workspace` in the container
* Run `jupyter notebook` in the foreground
* Map an available host port to that notebook server
* Print a message to the user directing them to that port

As starting a jupyter notebook itself prints the port it's running on, the subcommand probably wants to swallow the jupyter console message and replace it.

Thinking about the subcommand naming, longer term we may want to start the notebook with different options, for example with a R kernel instead of a Python kernel.  `opensafely python-notebook` would probably be fine.

There is prior art here, dating from when we were trying to make a generalisable, portable jupyter environment. The approach there was to first do a `docker build` to create an image that includes the local `requirements.txt`, _then_ do the above steps.

Accordingly, [this file](https://github.com/ebmdatalab/datalab-notebook-template/blob/master/run.py) contains some functions that may be useful for the port-selection and jupyter-message-swallowing parts.

When this is done, the README [here](https://github.com/opensafely/covid-vaccine-preliminary-uptake-study) may need updating; certainly its `run.py` and `run.exe` should be removed; and we should write some documentation in the main docs

**Comment by bloodearnest** [comment]
A few thoughts:

 - we can open a webbrowser window automatically with `webbrowser.open()`. Alternatively, the vscode notebook editor is better, so there should probably be a flag to enable/disable the opening.

 - as we're running inside docker, we can fix the internal jupyter port and point to the docker container's ip rather publishing on localhost, which avoids the port issues altogether. If they need to share it externally, we can add a --port option and then map it.

 - we don't want to support additional requirements.txt in the opensafely use case - you get what you get.

**Comment by bloodearnest** [comment]
Fixed in #84
