### ISSUE TITLE
`upgrade` command reports error on Windows (but seems to work anyway)

### ISSUE THREAD

**Issue by evansd** [opensafely-core/opensafely-cli#36]
Running `opensafely upgrade` on Windows reports an error:
```console
$ opensafely --version
Warning: there is a newer version of opensafely available - please run 'opensafely upgrade' to update to 1.6.2

opensafely v1.6.0

$ opensafely upgrade
Collecting opensafely==1.6.2
  Using cached opensafely-1.6.2-py3-none-any.whl (699 kB)
Installing collected packages: opensafely
  Attempting uninstall: opensafely
    Found existing installation: opensafely 1.6.0
    Uninstalling opensafely-1.6.0:
      Successfully uninstalled opensafely-1.6.0
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\dave\\AppData\\Local\\Temp\\pip-uninstall-qxxt6o_c\\opensafely.exe'
Consider using the `--user` option or check the permissions.

Command '['pip', 'install', '--upgrade', 'opensafely==1.6.2']' returned non-zero exit status 1.

$ opensafely --version
opensafely v1.6.2
```

Presumably this is because Windows won't let you write to the running executable. However the update still works anyway, because the entrypoint executable is just a thin wrapper to run Python in the correct venv and pointing to the correct module, and so it doesn't vary at all between versions.

So in one sense this doesn't really matter much. But the error message will no doubt cause confusion. And I suppose we can't guarantee that there won't be cases in future where updating the entrypoint _is_ important.

I think our options are (in decreasing order of laziness):

 1. Do nothing.
 
 2. Print a notice (either before or after pip runs) saying that the error can be ignored.
 
 3. Filter the output from `pip` and remove this specific warning.
 
 4. Try to run `pip` in a process that runs after the parent has executed. I don't know enough about the Windows process model to know how do-able this is. But perhaps if we invoke the subprocess like [this](https://stackoverflow.com/a/12854376) and then exit immediately, it will still work?

**Comment by bloodearnest** [comment]
Hmm, ok so 1.6.2 onwards (see #35) means we now do [sys.executable, "-m", "pip", "install", "upgrade"]

Unfortunately, we can't test that that change fixes it until we release 1.6.3+!

**Comment by alexwalkercebm** [comment]
I've seen the same thing happen when `pip install --upgrade`ing other packages on Windows notably upgrading `pip` itself.

**Comment by evansd** [comment]
Update: we can sort of get this to work by running `python -m pip --upgrade` in a detached process and then exiting immediately so that by the time pip wants to replace `opensafely.exe` it's no longer running.
```py
subprocess.Popen(
    [sys.executable, "-m", "pip", "install", "--upgrade", pkg]
)
sys.exit(0)
```

The downside of this is that console prompt returns immediately and then pip's output appears which is slightly confusing.

You'd think we could prevent this by using `os.execv()` to replace the current process but there's no such thing as process replacement on Windows (the `execv` function exists, but it's just a [wrapper around](https://bugs.python.org/issue19124#msg198599) spawn-then-exit).

I don't see a way of working around this. We have to exit the parent process in order for the executable to be updated, and as soon as we do that the console prompt will appear. Maybe our best bet is to print a warning beforehand that it's going to look a bit odd? At least the update works correctly this way, and there are no misleading error messages.

**Comment by evansd** [comment]
Final option: don't try to handle upgrades ourselves on Windows at all; just print the command for the user to copy-paste.

On Windows the version check prompt would display something like:
```
Warning: there is a newer version of opensafely available (1.6.2) - please upgrade by running:
    python -m pip install --upgrade opensafely
```

And if you did run `opensafely upgrade` directly it would say "Sorry, this command can't be used on Windows. Please run ..."

**Comment by evansd** [comment]
Haha! So there _is_ a way to do this and I know already that you will all love it.

```py
# Path to the current entrypoint binary (not the same as sys.executable)
bin_path = Path(sys.argv[0]).with_suffix(".exe")

# Move the binary out of the way (which you're allowed to do, even while it's running)
tmp_path = bin_path.with_suffix(".exe.tmp")
bin_path.replace(tmp_path)

# Immediately copy it back so that if something fails with the update everything should still work.
# If we get killed between the line above and the line below then we leave things in a broken state,
# but that's probably unlikely enough to not have to worry about
shutil.copy(tmp_path, bin_path)

# Continue with pip upgrade as normal, except no permissions errors this time
...
```

**Comment by bloodearnest** [comment]
Wat.

I give up.

**Comment by evansd** [comment]
Overnight I realised there's an even better version of the above which never risks leaving the system in a broken state and doesn't leave any temporary files lying around. Just make a temporary copy of the executable and then rename the copy over the original:
```py
# Path to the current entrypoint binary (not the same as sys.executable)
bin_path = Path(sys.argv[0]).with_suffix(".exe")

# Make a temporary copy
tmp_path = bin_path.with_suffix(".exe.tmp")
shutil.copy(bin_path, tmp_path)

# Replace currently executing binary with a copy of itself
tmp_path.replace(bin_path)

# The file at the path of the currently executing binary is no longer actually the
# currently executing binary (though it is identical with it) and so pip can happily
# upgrade it without any permissions errors
```

Works a treat.

Windows lol.

**Comment by bloodearnest** [comment]
I couldn't understand why this would work yesterday, and I though I was just tired at the end of the day.

But I slept well last night, and I still don't really understand why this works this morning. I started thinking that the handle is on the path not the inode, then I realised this is NTFS and You Know Nothing, Jon Snow.

But I'll take it.
