### ISSUE TITLE
Add antiviral eligibility functions to restricted list

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/opensafely-cli#97]
Once https://github.com/opensafely-core/cohort-extractor/issues/713 is in progress and function names decided, these should be added to https://github.com/opensafely-core/opensafely-cli/blob/main/opensafely/check.py#L12 before deployment

**Comment by rebkwok** [comment]
@Jongmassey @HelenCEBM @acagreen17 I'm doing this one now - are there specific study repos yet that should be allowed access to the therapeutics dataset?

**Comment by HelenCEBM** [comment]
Think it's just this atm: https://github.com/opensafely/antibody-and-antiviral-deployment
