### ISSUE TITLE
Add ISARIC to restricted dataset list 

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/opensafely-cli#99]
PR to add ISARIC to cohortextractor in progress https://github.com/opensafely-core/cohort-extractor/pull/730 

functions should be added to restricted list before this is deployed

**Comment by rebkwok** [comment]
Yes, that's fine - once the other one is in I'll add this one too

**Comment by rebkwok** [comment]
@Jongmassey  Are there any study repos to add for isaric yet?

**Comment by Jongmassey** [comment]
https://github.com/opensafely/hdruk-os-covid-paeds @amirmehrkar  can you confirm?
